name: Trigger Jenkins

on:
  push:
    branches: main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -X POST http://ip10-0-20-7-d0dh37g05akh4glkf9hg-8080.direct.lab-boris.fr/job/iac-pipeline/build --user "admin:8ec5302af5ee4dfa9169c116aac301d7" 
